# Generated by Django 3.1.4 on 2021-01-19 05:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sleepin', '0002_auto_20210119_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sleep',
            new_name='Sleeptime',
        ),
        migrations.AlterModelOptions(
            name='sleeptime',
            options={'verbose_name_plural': 'Sleeptime'},
        ),
    ]
