# Generated by Django 3.1.4 on 2021-01-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleepin', '0003_auto_20210119_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleeptime',
            name='satisfaction_level',
        ),
    ]
