# Generated by Django 3.1.4 on 2021-01-20 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sleepin', '0004_remove_sleeptime_satisfaction_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='sleeptime',
            name='create_date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='sleeptime',
            name='wakeup_at',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='起床時間'),
        ),
    ]
