# Generated by Django 3.1.4 on 2021-01-20 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sleepin', '0005_auto_20210120_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeptime',
            name='sleep_at',
            field=models.TimeField(default='23:00', verbose_name='就寝時間'),
        ),
        migrations.AlterField(
            model_name='sleeptime',
            name='wakeup_at',
            field=models.TimeField(default='07:00', verbose_name='起床時間'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日時')),
                ('meal', models.TextField(blank=True, null=True, verbose_name='食事')),
                ('beverage', models.TextField(blank=True, null=True, verbose_name='飲料')),
                ('snack', models.TextField(blank=True, null=True, verbose_name='間食')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Meal',
            },
        ),
    ]
