# Generated by Django 3.1.4 on 2021-01-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepin', '0006_auto_20210120_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='beverage',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='snack',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_menu',
            field=models.TextField(blank=True, null=True, verbose_name='食事内容'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.CharField(choices=[('食事', '食事'), ('飲み物', '飲み物'), ('間食', '間食')], default='', max_length=30, verbose_name='食事'),
        ),
    ]
