# Generated by Django 3.1.4 on 2021-01-20 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sleepin', '0007_auto_20210120_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日時')),
                ('health', models.CharField(choices=[('トレーニング', 'トレーニング'), ('ウォーキング', 'ウォーキング'), ('ストレッチ', 'ストレッチ')], default='', max_length=30, verbose_name='運動')),
                ('health_menu', models.TextField(blank=True, null=True, verbose_name='運動内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Health',
            },
        ),
    ]
