# Generated by Django 3.1.4 on 2021-01-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepin', '0010_auto_20210126_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.CharField(choices=[('朝食', '朝食'), ('昼食', '昼食'), ('夕食', '夕食'), ('飲み物', '飲み物'), ('間食', '間食')], default='', max_length=30, verbose_name='食事'),
        ),
    ]
